version: '3.7'

services:
  danny-frontend:
    restart: unless-stopped
    image: dannymischa/uek223-extended_frontend:latest
    container_name: danny-frontend
    depends_on:
      - dannyBackend
    ports:
      - "8012:80"
  dannyBackend:
    restart: unless-stopped
    image: dannymischa/uek223-extended_backend:latest
    container_name: dannyBackend
    ports:
      - "8097:8080"

  danny-db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: danny-db
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
